service: customer-contact-from #Name of your App

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 iamRoleStatements:
   - Effect: Allow
     Action:
       - ses:*
     Resource: "*"
 memorySize: 512
 timeout: 15
 stage: stage
 region: us-east-2 # AWS region


functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY /

