/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d506ca5f-b676-453a-b5c9-c6e3554323d9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6RPO1yDhD",
    "aws_user_pools_web_client_id": "5br41rmhg7e7k936k4jp7g6uki",
    "oauth": {}
};

export default awsConfig;
